spring.application.name=auth-service
server.port=${SERVER_PORT:10000}
jwt.secret=${JWT_SECRET:change-this-secret-key-change-this-secret-key-12345}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:3zG8dtEHRZ1HPrp.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:xiTGrZLaehkv0z1y}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=${REDIS_HOST:singapore-keyvalue.render.com}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:e9gEMLPtG7jN92Zy2CSc2Lc5zRDaMj9k}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:true}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:fullstackprojectsbyhari@gmail.com}
spring.mail.password=${MAIL_PASSWORD:kqwhmhujhxbkkpli}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.mail.from=${MAIL_FROM:${MAIL_USERNAME:}}

app.frontend-url=${FRONTEND_URL:}
app.google.client-id=${GOOGLE_CLIENT_ID:418501129031-dutr02pmbkl2sjvk076fjp40tuim7f01.apps.googleusercontent.com}
app.email.consumer.enabled=${EMAIL_CONSUMER_ENABLED:true}

app.security.access-token-minutes=${ACCESS_TOKEN_MINUTES:15}
app.security.refresh-token-days=${REFRESH_TOKEN_DAYS:7}
app.security.email-verification-minutes=${EMAIL_VERIFICATION_MINUTES:30}
app.security.password-reset-minutes=${PASSWORD_RESET_MINUTES:15}
app.security.magic-link-minutes=${MAGIC_LINK_MINUTES:15}
app.security.access-cookie-name=${ACCESS_COOKIE_NAME:access_token}
app.security.access-cookie-path=${ACCESS_COOKIE_PATH:/api}
app.security.refresh-cookie-name=${REFRESH_COOKIE_NAME:refresh_token}
app.security.refresh-cookie-path=${REFRESH_COOKIE_PATH:/api}
app.security.refresh-cookie-same-site=${REFRESH_COOKIE_SAME_SITE:Lax}
app.security.secure-cookies=true
app.security.max-failed-logins=${MAX_FAILED_LOGINS:5}
app.security.lockout-duration-minutes=${LOCKOUT_DURATION_MINUTES:15}
